/*
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.ui.tests;

import com.google.inject.Injector;
import emn.fil.a3.SeleniumScript.ui.internal.SeleniumScriptActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SeleniumScriptUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SeleniumScriptActivator.getInstance().getInjector("emn.fil.a3.SeleniumScript");
	}

}
