/*
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.ui;

import com.google.inject.Injector;
import emn.fil.a3.SeleniumScript.ui.internal.SeleniumScriptActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SeleniumScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SeleniumScriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SeleniumScriptActivator.getInstance().getInjector(SeleniumScriptActivator.EMN_FIL_A3_SELENIUMSCRIPT);
	}
	
}
