/*
 * generated by Xtext 2.10.0
 */
package emn.fil.a3


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SeleniumScriptStandaloneSetup extends SeleniumScriptStandaloneSetupGenerated {

	def static void doSetup() {
		new SeleniumScriptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
