/*
 * generated by Xtext 2.10.0
 */
package emn.fil.a3


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SeleniumScriptRuntimeModule extends AbstractSeleniumScriptRuntimeModule {
}
