/*
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSeleniumScriptScopeProvider extends DelegatingScopeProvider {
}
