/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.ui;

import emn.fil.a3.ui.AbstractSeleniumScriptUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SeleniumScriptUiModule extends AbstractSeleniumScriptUiModule {
  public SeleniumScriptUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
