/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.seleniumScript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
