/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.seleniumScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends Expression
{
} // Primary
