/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.seleniumScript;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selectors</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link emn.fil.a3.seleniumScript.Selectors#getSelectors <em>Selectors</em>}</li>
 *   <li>{@link emn.fil.a3.seleniumScript.Selectors#getSlectors <em>Slectors</em>}</li>
 *   <li>{@link emn.fil.a3.seleniumScript.Selectors#getSelector <em>Selector</em>}</li>
 * </ul>
 *
 * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getSelectors()
 * @model
 * @generated
 */
public interface Selectors extends Expression
{
  /**
   * Returns the value of the '<em><b>Selectors</b></em>' containment reference list.
   * The list contents are of type {@link emn.fil.a3.seleniumScript.Selector}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selectors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selectors</em>' containment reference list.
   * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getSelectors_Selectors()
   * @model containment="true"
   * @generated
   */
  EList<Selector> getSelectors();

  /**
   * Returns the value of the '<em><b>Slectors</b></em>' containment reference list.
   * The list contents are of type {@link emn.fil.a3.seleniumScript.Selector}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Slectors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slectors</em>' containment reference list.
   * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getSelectors_Slectors()
   * @model containment="true"
   * @generated
   */
  EList<Selector> getSlectors();

  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference list.
   * The list contents are of type {@link emn.fil.a3.seleniumScript.Selector}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selector</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference list.
   * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getSelectors_Selector()
   * @model containment="true"
   * @generated
   */
  EList<Selector> getSelector();

} // Selectors
