/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.seleniumScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link emn.fil.a3.seleniumScript.Selector#getName <em>Name</em>}</li>
 *   <li>{@link emn.fil.a3.seleniumScript.Selector#getPropSelectors <em>Prop Selectors</em>}</li>
 * </ul>
 *
 * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getSelector()
 * @model
 * @generated
 */
public interface Selector extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getSelector_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link emn.fil.a3.seleniumScript.Selector#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Prop Selectors</b></em>' containment reference list.
   * The list contents are of type {@link emn.fil.a3.seleniumScript.PropSelector}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prop Selectors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop Selectors</em>' containment reference list.
   * @see emn.fil.a3.seleniumScript.SeleniumScriptPackage#getSelector_PropSelectors()
   * @model containment="true"
   * @generated
   */
  EList<PropSelector> getPropSelectors();

} // Selector
