/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.seleniumScript;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see emn.fil.a3.seleniumScript.SeleniumScriptFactory
 * @model kind="package"
 * @generated
 */
public interface SeleniumScriptPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "seleniumScript";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.fil.emn/a3/SeleniumScript";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "seleniumScript";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SeleniumScriptPackage eINSTANCE = emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl.init();

  /**
   * The meta object id for the '{@link emn.fil.a3.seleniumScript.impl.ScriptImpl <em>Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see emn.fil.a3.seleniumScript.impl.ScriptImpl
   * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getScript()
   * @generated
   */
  int SCRIPT = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__FUNCTIONS = 0;

  /**
   * The number of structural features of the '<em>Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link emn.fil.a3.seleniumScript.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see emn.fil.a3.seleniumScript.impl.FunctionImpl
   * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PARAMS = 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link emn.fil.a3.seleniumScript.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see emn.fil.a3.seleniumScript.impl.ExpressionImpl
   * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link emn.fil.a3.seleniumScript.impl.SelectorsImpl <em>Selectors</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see emn.fil.a3.seleniumScript.impl.SelectorsImpl
   * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectors()
   * @generated
   */
  int SELECTORS = 3;

  /**
   * The feature id for the '<em><b>Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTORS__SELECTORS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Slectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTORS__SLECTORS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTORS__SELECTOR = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Selectors</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTORS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link emn.fil.a3.seleniumScript.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see emn.fil.a3.seleniumScript.impl.SelectorImpl
   * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__SELECTORS = 1;

  /**
   * The feature id for the '<em><b>Prop Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__PROP_SELECTORS = 2;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link emn.fil.a3.seleniumScript.impl.PropSelectorImpl <em>Prop Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see emn.fil.a3.seleniumScript.impl.PropSelectorImpl
   * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getPropSelector()
   * @generated
   */
  int PROP_SELECTOR = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROP_SELECTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROP_SELECTOR__PARAM = 1;

  /**
   * The number of structural features of the '<em>Prop Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROP_SELECTOR_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link emn.fil.a3.seleniumScript.Script <em>Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Script</em>'.
   * @see emn.fil.a3.seleniumScript.Script
   * @generated
   */
  EClass getScript();

  /**
   * Returns the meta object for the containment reference list '{@link emn.fil.a3.seleniumScript.Script#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see emn.fil.a3.seleniumScript.Script#getFunctions()
   * @see #getScript()
   * @generated
   */
  EReference getScript_Functions();

  /**
   * Returns the meta object for class '{@link emn.fil.a3.seleniumScript.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see emn.fil.a3.seleniumScript.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link emn.fil.a3.seleniumScript.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see emn.fil.a3.seleniumScript.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link emn.fil.a3.seleniumScript.Function#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see emn.fil.a3.seleniumScript.Function#getParams()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Params();

  /**
   * Returns the meta object for class '{@link emn.fil.a3.seleniumScript.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see emn.fil.a3.seleniumScript.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link emn.fil.a3.seleniumScript.Selectors <em>Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selectors</em>'.
   * @see emn.fil.a3.seleniumScript.Selectors
   * @generated
   */
  EClass getSelectors();

  /**
   * Returns the meta object for the containment reference list '{@link emn.fil.a3.seleniumScript.Selectors#getSelectors <em>Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Selectors</em>'.
   * @see emn.fil.a3.seleniumScript.Selectors#getSelectors()
   * @see #getSelectors()
   * @generated
   */
  EReference getSelectors_Selectors();

  /**
   * Returns the meta object for the containment reference list '{@link emn.fil.a3.seleniumScript.Selectors#getSlectors <em>Slectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Slectors</em>'.
   * @see emn.fil.a3.seleniumScript.Selectors#getSlectors()
   * @see #getSelectors()
   * @generated
   */
  EReference getSelectors_Slectors();

  /**
   * Returns the meta object for the containment reference list '{@link emn.fil.a3.seleniumScript.Selectors#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Selector</em>'.
   * @see emn.fil.a3.seleniumScript.Selectors#getSelector()
   * @see #getSelectors()
   * @generated
   */
  EReference getSelectors_Selector();

  /**
   * Returns the meta object for class '{@link emn.fil.a3.seleniumScript.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see emn.fil.a3.seleniumScript.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link emn.fil.a3.seleniumScript.Selector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see emn.fil.a3.seleniumScript.Selector#getName()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Name();

  /**
   * Returns the meta object for the containment reference list '{@link emn.fil.a3.seleniumScript.Selector#getSelectors <em>Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Selectors</em>'.
   * @see emn.fil.a3.seleniumScript.Selector#getSelectors()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Selectors();

  /**
   * Returns the meta object for the containment reference list '{@link emn.fil.a3.seleniumScript.Selector#getPropSelectors <em>Prop Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prop Selectors</em>'.
   * @see emn.fil.a3.seleniumScript.Selector#getPropSelectors()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_PropSelectors();

  /**
   * Returns the meta object for class '{@link emn.fil.a3.seleniumScript.PropSelector <em>Prop Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prop Selector</em>'.
   * @see emn.fil.a3.seleniumScript.PropSelector
   * @generated
   */
  EClass getPropSelector();

  /**
   * Returns the meta object for the attribute '{@link emn.fil.a3.seleniumScript.PropSelector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see emn.fil.a3.seleniumScript.PropSelector#getName()
   * @see #getPropSelector()
   * @generated
   */
  EAttribute getPropSelector_Name();

  /**
   * Returns the meta object for the attribute '{@link emn.fil.a3.seleniumScript.PropSelector#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see emn.fil.a3.seleniumScript.PropSelector#getParam()
   * @see #getPropSelector()
   * @generated
   */
  EAttribute getPropSelector_Param();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SeleniumScriptFactory getSeleniumScriptFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link emn.fil.a3.seleniumScript.impl.ScriptImpl <em>Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see emn.fil.a3.seleniumScript.impl.ScriptImpl
     * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getScript()
     * @generated
     */
    EClass SCRIPT = eINSTANCE.getScript();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCRIPT__FUNCTIONS = eINSTANCE.getScript_Functions();

    /**
     * The meta object literal for the '{@link emn.fil.a3.seleniumScript.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see emn.fil.a3.seleniumScript.impl.FunctionImpl
     * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__PARAMS = eINSTANCE.getFunction_Params();

    /**
     * The meta object literal for the '{@link emn.fil.a3.seleniumScript.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see emn.fil.a3.seleniumScript.impl.ExpressionImpl
     * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link emn.fil.a3.seleniumScript.impl.SelectorsImpl <em>Selectors</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see emn.fil.a3.seleniumScript.impl.SelectorsImpl
     * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectors()
     * @generated
     */
    EClass SELECTORS = eINSTANCE.getSelectors();

    /**
     * The meta object literal for the '<em><b>Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTORS__SELECTORS = eINSTANCE.getSelectors_Selectors();

    /**
     * The meta object literal for the '<em><b>Slectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTORS__SLECTORS = eINSTANCE.getSelectors_Slectors();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTORS__SELECTOR = eINSTANCE.getSelectors_Selector();

    /**
     * The meta object literal for the '{@link emn.fil.a3.seleniumScript.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see emn.fil.a3.seleniumScript.impl.SelectorImpl
     * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__NAME = eINSTANCE.getSelector_Name();

    /**
     * The meta object literal for the '<em><b>Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__SELECTORS = eINSTANCE.getSelector_Selectors();

    /**
     * The meta object literal for the '<em><b>Prop Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__PROP_SELECTORS = eINSTANCE.getSelector_PropSelectors();

    /**
     * The meta object literal for the '{@link emn.fil.a3.seleniumScript.impl.PropSelectorImpl <em>Prop Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see emn.fil.a3.seleniumScript.impl.PropSelectorImpl
     * @see emn.fil.a3.seleniumScript.impl.SeleniumScriptPackageImpl#getPropSelector()
     * @generated
     */
    EClass PROP_SELECTOR = eINSTANCE.getPropSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROP_SELECTOR__NAME = eINSTANCE.getPropSelector_Name();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROP_SELECTOR__PARAM = eINSTANCE.getPropSelector_Param();

  }

} //SeleniumScriptPackage
