/*
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSeleniumScriptValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(emn.fil.a3.seleniumScript.SeleniumScriptPackage.eINSTANCE);
		return result;
	}
	
}
