/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3;

import emn.fil.a3.SeleniumScriptStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SeleniumScriptStandaloneSetup extends SeleniumScriptStandaloneSetupGenerated {
  public static void doSetup() {
    SeleniumScriptStandaloneSetup _seleniumScriptStandaloneSetup = new SeleniumScriptStandaloneSetup();
    _seleniumScriptStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
