/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3;

import emn.fil.a3.AbstractSeleniumScriptRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SeleniumScriptRuntimeModule extends AbstractSeleniumScriptRuntimeModule {
}
