/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.scoping;

import emn.fil.a3.scoping.AbstractSeleniumScriptScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SeleniumScriptScopeProvider extends AbstractSeleniumScriptScopeProvider {
}
