/*
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SeleniumScriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("emn/fil/a3/parser/antlr/internal/InternalSeleniumScript.tokens");
	}
}
