/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.validation;

import emn.fil.a3.validation.AbstractSeleniumScriptValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SeleniumScriptValidator extends AbstractSeleniumScriptValidator {
}
