/**
 * generated by Xtext 2.10.0
 */
package emn.fil.a3.ui.contentassist;

import emn.fil.a3.ui.contentassist.AbstractSeleniumScriptProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SeleniumScriptProposalProvider extends AbstractSeleniumScriptProposalProvider {
}
